import React from 'react';
import {
  FaBone, FaFlask, FaAtom, FaMicroscope, FaHeartbeat, FaBacteria,
  FaShieldAlt, FaStethoscope, FaPills, FaSearch, FaCamera,
  FaUserMd, FaBaby, FaCut, FaHeart, FaBrain, FaRadiation,
  FaHospital, FaAmbulance, FaBalanceScale, FaGraduationCap,
  FaLungs, FaVial, FaLeaf, FaPrescriptionBottle, FaSkullCrossbones,
  FaGlobeAmericas, FaFileMedical, FaChartBar, FaDna, FaTint,
  FaFemale, FaHandPaper, FaUserInjured, FaHardHat, FaHeadphonesAlt,
  FaEye, FaUserFriends, FaSeedling, FaWheelchair, FaWeight,
} from 'react-icons/fa';

const moduleIconMap = {
  anatomie: <FaBone />,
  biochimie: <FaFlask />,
  biophysique: <FaAtom />,
  biostatistiques: <FaChartBar />,
  histologie: <FaMicroscope />,
  physiologie: <FaHeartbeat />,
  cytologie: <FaMicroscope />,
  embryologie: <FaBaby />,
  physique: <FaAtom />,
  microbiologie: <FaBacteria />,
  bactériologie: <FaBacteria />,
  virologie: <FaBacteria />,
  parasitologie: <FaBacteria />,
  infectiologie: <FaBacteria />,
  immunologie: <FaShieldAlt />,
  sémiologie: <FaStethoscope />,
  pharmacologie: <FaPills />,
  anatomopathologie: <FaMicroscope />,
  'anatomie pathologique': <FaMicroscope />,
  radiologie: <FaCamera />,
  imagerie: <FaCamera />,
  'médecine interne': <FaUserMd />,
  interne: <FaUserMd />,
  pédiatrie: <FaBaby />,
  néonatologie: <FaBaby />,
  chirurgie: <FaCut />,
  cardiologie: <FaHeart />,
  cardio: <FaHeart />,
  coeur: <FaHeart />,
  cœur: <FaHeart />,
  neurologie: <FaBrain />,
  neuro: <FaBrain />,
  cerveau: <FaBrain />,
  oncologie: <FaRadiation />,
  onco: <FaRadiation />,
  cancer: <FaRadiation />,
  réanimation: <FaHospital />,
  urgences: <FaAmbulance />,
  éthique: <FaBalanceScale />,
  déontologie: <FaBalanceScale />,
  internat: <FaGraduationCap />,
  préparation: <FaGraduationCap />,
  pneumologie: <FaLungs />,
  pneumo: <FaLungs />,
  poumon: <FaLungs />,
  gastro: <FaVial />,
  gastroentérologie: <FaVial />,
  digestion: <FaVial />,
  chimie: <FaFlask />,
  botanique: <FaLeaf />,
  plantes: <FaLeaf />,
  pharmacie: <FaPrescriptionBottle />,
  galénique: <FaPrescriptionBottle />,
  officine: <FaPrescriptionBottle />,
  hospitalière: <FaPrescriptionBottle />,
  toxicologie: <FaSkullCrossbones />,
  'santé publique': <FaGlobeAmericas />,
  épidémiologie: <FaGlobeAmericas />,
  génétique: <FaDna />,
  urinaire: <FaTint />,
  néphrologie: <FaTint />,
  endocrinien: <FaBalanceScale />,
  endocrinologie: <FaBalanceScale />,
  gynécologie: <FaFemale />,
  reproducteur: <FaFemale />,
  psychologie: <FaUserFriends />,
  psychiatrie: <FaUserFriends />,
  locomoteur: <FaWheelchair />,
  dermatologie: <FaHandPaper />,
  gériatrie: <FaUserInjured />,
  'maladies systémiques': <FaHeartbeat />,
  'médecine du travail': <FaHardHat />,
  orl: <FaHeadphonesAlt />,
  ophtalmologie: <FaEye />,
  ssh: <FaGlobeAmericas />,
  digestif: <FaStethoscope />,
  hématopoïétique: <FaTint />,
  'cardio-respiratoire': <FaHeart />,
  'système nerveux': <FaBrain />,
};

const fallbackIcon = <FaFileMedical />;

export const getModuleIcon = (moduleName) => {
  const name = (moduleName || '').toLowerCase();
  for (const [key, icon] of Object.entries(moduleIconMap)) {
    if (name.includes(key)) return icon;
  }
  return fallbackIcon;
};
